//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace schoolDB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class schoolDBEntities : DbContext
    {
        public schoolDBEntities()
            : base("name=schoolDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Table_Attendnce> Table_Attendnce { get; set; }
        public virtual DbSet<Table_class> Table_class { get; set; }
        public virtual DbSet<Table_days> Table_days { get; set; }
        public virtual DbSet<Table_Modules> Table_Modules { get; set; }
        public virtual DbSet<Table_parents> Table_parents { get; set; }
        public virtual DbSet<Table_paymentsDetails> Table_paymentsDetails { get; set; }
        public virtual DbSet<Table_programme> Table_programme { get; set; }
        public virtual DbSet<Table_students> Table_students { get; set; }
        public virtual DbSet<Table_Teacher> Table_Teacher { get; set; }
        public virtual DbSet<Table_times> Table_times { get; set; }
        public virtual DbSet<Table_admin> Table_admin { get; set; }
    }
}
