//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace schoolDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_paymentsDetails
    {
        public int id { get; set; }
        public string type { get; set; }
        public Nullable<decimal> amount { get; set; }
        public Nullable<decimal> blance { get; set; }
        public Nullable<decimal> recette { get; set; }
        public string sumistre { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<int> id_parents { get; set; }
    
        public virtual Table_parents Table_parents { get; set; }
    }
}
