//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace schoolDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_Attendnce
    {
        public int id { get; set; }
        public Nullable<int> id_students { get; set; }
        public string remark { get; set; }
        public Nullable<System.DateTime> date { get; set; }
    
        public virtual Table_students Table_students { get; set; }
    }
}
