//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace schoolDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_class
    {
        public int id { get; set; }
        public Nullable<int> id_student { get; set; }
        public Nullable<int> id_teacher { get; set; }
        public Nullable<int> id_modules { get; set; }
        public Nullable<int> id_times { get; set; }
    
        public virtual Table_Modules Table_Modules { get; set; }
        public virtual Table_students Table_students { get; set; }
        public virtual Table_Teacher Table_Teacher { get; set; }
        public virtual Table_times Table_times { get; set; }
    }
}
